name: Deploy Azure Function

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # match your Function App runtime

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt --target package

    - name: Copy app files
      run: |
        cp -r function_app/* package/

    - name: Zip package
      run: |
        cd package
        zip -r ../functionapp.zip .

    - name: Deploy to Azure Function
      uses: azure/functions-action@v1
      with:
        app-name: 'TranscriberAPI2'
        package: functionapp.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
