# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - TranscriberAPI2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'deploy' # folder to deploy
  PYTHON_VERSION: '3.11' # Python version for Azure Function

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir deploy
          # Copy app code into deploy folder, excluding .github and existing deploy folder
          shopt -s extglob
          cp -r !(deploy|.github) deploy/

      - name: Install dependencies into deploy folder
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --target deploy

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d deploy
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F510A41D064A404ABC55D1B737DECEB7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7317E31C08A64F9592FDF7807AC2D63A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD6D1C44C1734D4499026F132E45D913 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'TranscriberAPI2'
          slot-name: 'Production'
          package: deploy
